CREATE DATABASE IF NOT EXISTS jeizi_production;
USE jeizi_production;

CREATE TABLE IF NOT EXISTS teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  shortname VARCHAR(50) DEFAULT NULL,
  logo VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS matches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  match_no INT DEFAULT 1,
  blue_team_id INT DEFAULT NULL,
  red_team_id INT DEFAULT NULL,
  mode VARCHAR(10) DEFAULT 'BO3',
  title VARCHAR(255) DEFAULT 'Match',
  queue_order INT DEFAULT 1,
  blue_score INT DEFAULT 0,
  red_score INT DEFAULT 0,
  status VARCHAR(50) DEFAULT 'queued',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (blue_team_id) REFERENCES teams(id) ON DELETE SET NULL,
  FOREIGN KEY (red_team_id) REFERENCES teams(id) ON DELETE SET NULL
);
